### ISSUE TITLE
Installing dependencies

### ISSUE THREAD

**Issue by justheuristic** [yandexdataschool/Practical_RL#1]
Any issues concerning installation can just as well be sent here.

We assume that you have basic data science toolkit (sklearn, numpy/scipy/pandas). Basically whatever comes with default anaconda distribution.
* Anaconda: https://www.continuum.io/downloads (or simply use python with numpy/sklearn)

The majority of course assignments assignments use OpenAI gym
* Installing gym: https://github.com/openai/gym#installation

If you don't/can't install that (e.g. you use windows and installation is tricky), there's a docker container contributed to the course. 

### Deep learning
You will also need one of the following three stacks:

* __PyTorch__:
  * Installing on Linux / Mac OS: http://pytorch.org/
  * Installing on windows: https://anaconda.org/peterjc123/pytorch (CPU only)

* __TensorFlow__:
  * `pip install tensorflow`
  * `pip install keras`
  * [Detailed guide](https://www.tensorflow.org/install/)

* __Theano__:
  - [only theano and lasagne](http://lasagne.readthedocs.io/en/latest/user/installation.html) - **pick [bleeding edge](http://lasagne.readthedocs.io/en/latest/user/installation.html#bleeding-edge-version) version**
  - [all 3 of them](http://agentnet.readthedocs.io/en/latest/user/install.html)

The frameworks can be easily installed on Mac OS and Linux. Windows installation is, a bit tougher, so if you don't feel like it, try using docker (e.g. kitematic gui or console on windows).

### Install docker 
* Simple interface for docker: [kitematic](https://kitematic.com/) (all platforms)
* Guide for [windows](https://docs.docker.com/docker-for-windows/), [linux](https://docs.docker.com/engine/installation/), or [macOS](https://docs.docker.com/docker-for-mac/).

__Clone__ docker repo: https://hub.docker.com/r/justheuristic/practical_rl
(or just ```docker pull justheuristic/practical_rl``` if you have docker shell)

If you want to build it yourself, use these [instructions](https://github.com/yandexdataschool/Practical_RL/tree/master/docker).

If you run into any trouble, feel free to post here, even if it's like "i don't know what the hell all these letters mean!!!".

**Comment by LecJackS** [comment]
One question: We'll use **Python 2.7** or **3** in this course? I couldn't find that anywhere.

**Comment by arogozhnikov** [comment]
@LecJackS, I've commented your question in the gitter chat.

**Comment by LecJackS** [comment]
Thanks @arogozhnikov , I'll copy it here:

> @LecJackS notebooks are written in the way to work in both, so whichever you prefer.
> If you have no preference, then please use 2.7

**Comment by reppolice** [comment]
The Linux "native docker" instructions in Practical_RL/tree/master/docker, in addition to needing better formatting (I think right now there is no carriage return between the two docker commands), needed the -it and -v parameters moved in front of the image name, otherwise my Ubuntu docker was giving me errors.

**Comment by dniku** [comment]
I'm reasonably certain that this issue can be now closed. Let's open more specific issues as needed.

**Comment by dniku** [comment]
@nikikotecha we don't publish the solutions to discourage the students who take this course in-person from cheating.

Also, please open separate issues for similar questions instead of posting them here.
