### ISSUE TITLE
enhancement - download associated youtube content

### ISSUE THREAD

**Issue by johndpope** [yandexdataschool/Practical_RL#10]
**OSX** 
https://github.com/rg3/youtube-dl
```
brew install youtube-dl
youtube-dl https://www.youtube.com/watch\?v\=2pWv7GOvuf0
TODO - dig up every youtube link
```

**Comment by justheuristic** [comment]
Wow, nice idea!
We'll add scripts for every week then, so that one can do ./week1/download_videos.sh or bash ./*/download_videos.sh .
Is that okay or is there a strictly better way?

**Comment by johndpope** [comment]
I think simple is good - a one shot script / copy and paste to grab entire set and save to a folder.
otherwise - you going to have to cd into each directory and chmod script 

youtube-dl https://www.youtube.com/watch\?v\=2pWv7GOvuf0
youtube-dl https://www.youtube.com/watch\?v\=23423234234 
youtube-dl https://www.youtube.com/watch\?v\=23423234235
youtube-dl https://www.youtube.com/watch\?v\=23423234236
youtube-dl https://www.youtube.com/watch\?v\=23423234237

**Comment by justheuristic** [comment]
done. 
https://github.com/yandexdataschool/Practical_RL/commit/b788f297b512bf8218f99a88552d854e9895ea63
If you meant something else, pls comment.
