### ISSUE TITLE
Bad error message for an expired Coursera token

### ISSUE THREAD

**Issue by Pastafarianist** [yandexdataschool/Practical_RL#102]
See https://www.coursera.org/learn/practical-rl/discussions/weeks/1/threads/xwiluv0AEeiI8gouSncDyg. The error should be handled explicitly and a good message should be presented to the user.

Line in question: https://github.com/yandexdataschool/Practical_RL/blob/coursera/grading.py#L34

**Comment by justheuristic** [comment]
Thanks!
https://github.com/yandexdataschool/Practical_RL/commit/3867dda6fc4537f383424d42962868d40d1cf524
