### ISSUE TITLE
Try PyVirtualDisplay instead of xvfb for prettier first cell

### ISSUE THREAD

**Issue by Pastafarianist** [yandexdataschool/Practical_RL#103]
https://pyvirtualdisplay.readthedocs.io/en/latest/

**Comment by justheuristic** [comment]
The first attempt by @Fritz449 has shown that getting it to work on every platform is waay more gruesome than plain xvfb. 

Unless there are any objections, we'd rather stick to xvfb.

**Comment by Pastafarianist** [comment]
No objections.
