### ISSUE TITLE
Weird Dockerfile

### ISSUE THREAD

**Issue by Pastafarianist** [yandexdataschool/Practical_RL#106]
The following blocks are identical:

https://github.com/yandexdataschool/Practical_RL/blob/master/docker/Dockerfile#L31-L46

https://github.com/yandexdataschool/Practical_RL/blob/master/docker/Dockerfile#L51-L66

Is this expected?

**Comment by Pastafarianist** [comment]
Didn't notice that the second section is for py3. Do we definitely need py2 deps?

**Comment by justheuristic** [comment]
I am afraid so (HSE requirements). We'll discontinue it as soon as we'll get a chance to change the official requirements

**Comment by justheuristic** [comment]
https://pythonclock.org/
