### ISSUE TITLE
coursera/week5_policy_based/practice_a3c.ipynb uses reward_scale=0.01, but grader doesn't

### ISSUE THREAD

**Issue by Pastafarianist** [yandexdataschool/Practical_RL#109]
Coursera grader accepts score at least 5000, but with 0.01 scaling that's 5x SotA.

Possible ways to fix:

1. Remove scaling
2. Rescale score in grader submission
3. Rescale grader lower bound

**Comment by justheuristic** [comment]
Thanks!
