### ISSUE TITLE
joblib+gym 

### ISSUE THREAD

**Issue by neychev** [yandexdataschool/Practical_RL#11]
joblib generates identical sessions if games are run in multiple threads. Simple notebook that reproduce the problem on my machine is attached.

[Notebook on gist](https://gist.github.com/neychev/508402689c65db1a9cee1b07abe22054)

**Comment by justheuristic** [comment]
Hello!
It may be a good idea to create new env in the "play this thing" function. Afair we talked about this in PM. 

Please tell us if that worked out.

**Comment by neychev** [comment]
Ok, it has done the trick.

To make game sessions unique:
1. In the process that plays the game create new environment:
e.g. env = gym.make('Taxi-v1')
(don't forget to close the env when it's done)

2. Generate random seed for each game session:
 e.g. np.random.seed()

For me it works. Thanks for your consideration.

**Comment by nambrot** [comment]
Do you have a sample gist laying around for your work? I'm trying to use joblib as well right now, but it doesn't seem to yield any improvements, despite creating and closing environments for each session
