### ISSUE TITLE
week2, mdp viz: lightgreen is not a known color

### ISSUE THREAD

**Issue by NickVeld** [yandexdataschool/Practical_RL#119]
![image](https://user-images.githubusercontent.com/17028401/52563934-c6701000-2e13-11e9-9e0c-5ad7619cb5a4.png)

Some software combination causes this.

Ways to solve:
1) choose other color, green for example
2) use numeric color encoding

**Comment by neer201** [comment]
> ![image](https://user-images.githubusercontent.com/17028401/52563934-c6701000-2e13-11e9-9e0c-5ad7619cb5a4.png)
> 
> Some software combination cause this.
> 
> Ways to solve:
> 
> 1. choose other color, green for example
> 2. use numeric color encoding

Cool!

**Comment by neer201** [comment]
> ![image](https://user-images.githubusercontent.com/17028401/52563934-c6701000-2e13-11e9-9e0c-5ad7619cb5a4.png)
> 
> Some software combination cause this.
> 
> Ways to solve:
> 
> 1. choose other color, green for example
> 2. use numeric color encoding

Could you please write your some software combination?

**Comment by justheuristic** [comment]
(PR merged, thanks!)
