### ISSUE TITLE
week2_model_based/practice_vi.ipynb: ValueError: 'a' must be 1-dimensional

### ISSUE THREAD

**Issue by Pastafarianist** [yandexdataschool/Practical_RL#135]
https://www.coursera.org/learn/practical-rl/discussions/all/threads/LgMOpTNgEem3MQ5UkLSNGA/replies/gimM1zZ3EemT5gqU4rjdog

```
Traceback (most recent call last)
<ipython-input-34-c418a9988166> in <module>
      4     a = get_optimal_action(mdp, state_values, s, gamma)
      5     print("optimal", a)
----> 6     s, r, done, _ = mdp.step(a)
      7     mdp.render()
      8     if done: break

~\Downloads\Practical_RL\week2_model_based\mdp.py in step(self, action)
     91         """ take action, return next_state, reward, is_done, empty_info """
     92         possible_states, probs = zip(*self.get_next_states(self._current_state, action).items())
---> 93         next_state = np.random.choice(possible_states, p=probs)
     94         reward = self.get_reward(self._current_state, action, next_state)
     95         is_done = self.is_terminal(next_state)

mtrand.pyx in mtrand.RandomState.choice()

ValueError: 'a' must be 1-dimensional
```

Line that throws the exception: https://github.com/yandexdataschool/Practical_RL/blob/03cf1de/week2_model_based/mdp.py#L93

This is caused by https://github.com/yandexdataschool/Practical_RL/commit/03cf1de955d7e19e8cdf556c3cb20622a36f8cab.

Turns out, `np.random.choice` does not support selection from multidimensional arrays. This can be fixed as follows:

```python
next_state = possible_states[np.random.choice(np.arange(possible_states.shape[0]), p=probs)]
```

I will make a PR shortly.

**Comment by justheuristic** [comment]
LGTM в ретроспективе

**Comment by Anil1331** [comment]
After pulling this patch I am facing below issue

---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-24-e53940f14491> in <module>
      6     value_iteration,
      7     "matcha.11@samsung.com",
----> 8     "j8ASrtt1qmFrAMZi")

~\Downloads\Practical_RL\week2_model_based\submit.py in submit_assigment(get_action_value, get_new_state_value, get_optimal_action, value_iteration, email, token)
     80     rewards = []
     81     for _ in range(10000):
---> 82         s, r, done, _ = mdp.step(get_optimal_action(mdp, state_values, s, gamma))
     83         rewards.append(r)
     84 

~\Downloads\Practical_RL\week2_model_based\mdp.py in step(self, action)
     99     def step(self, action):
    100         """ take action, return next_state, reward, is_done, empty_info """
--> 101         possible_states, probs = zip(*self.get_next_states(self._current_state, action).items())
    102         next_state = weighted_choice(possible_states, p=probs)
    103         reward = self.get_reward(self._current_state, action, next_state)

~\Downloads\Practical_RL\week2_model_based\mdp.py in get_next_states(self, state, action)
     73     def get_next_states(self, state, action):
     74         """ return a dictionary of {next_state1 : P(next_state1 | state, action), next_state2: ...} """
---> 75         assert action in self.get_possible_actions(state), "cannot do action %s from state %s" % (action, state)
     76         return self._transition_probs[state][action]
     77 

AssertionError: cannot do action None from state s3

**Comment by Pastafarianist** [comment]
(Replied [here](https://www.coursera.org/learn/practical-rl/discussions/all/threads/LgMOpTNgEem3MQ5UkLSNGA/replies/gimM1zZ3EemT5gqU4rjdog/comments/TfAEHTg4EemS1w7nODGJ4A), as this is probably not our bug.)
