### ISSUE TITLE
Kernel silent death on remote machie (xvfb?)

### ISSUE THREAD

**Issue by neychev** [yandexdataschool/Practical_RL#14]
On remote machine with no display the following actions causes some problem in python output: the kernel dies every time on matplotlib.pyplot or tqdm called.
Also, env.render() from gym also causes kernel death.

The algorithm (copied from week4 seminar):
``` python 
import os
if type(os.environ.get("DISPLAY")) is not str or len(os.environ.get("DISPLAY"))==0:
    !bash ../xvfb start
    %env DISPLAY=:1

import gym
import numpy as np, pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# for now kernel is still alive. plt. commands work fine

env = gym.make("CartPole-v0")
env.reset()
n_actions = env.action_space.n
state_dim = env.observation_space.shape

plt.imshow(env.render("rgb_array", close=True))
```
Kernel dies on the last string. After restart matplotlib also causes kernel death. Restarting the whole jupyter doesn't help either. Creating new env (in conda) - no use.
The only way I found yet is uninstalling Anaconda and installing all needed packages again.

That's what definitely should not happen to any remote machine.

**Comment by justheuristic** [comment]
Something's definitely wrong with anaconda.
Does the problem persist with the [course docker](https://github.com/yandexdataschool/Practical_RL/tree/master/docker)?

Also please try the same script in python _console_ rather than jupyter - it should reveal the actual error message.

**Comment by neychev** [comment]
Using python _console_ it fails with 
``` bash
Starting virtual X frame buffer: Xvfb.
[2017-03-16 14:25:30,059] Making new env: CartPole-v0
Illegal instruction``` 
even with `python --verbose`

**Comment by neychev** [comment]
I guess, there may be a problem with `xvfb`:
`ps aux | grep xvfb` can't find anything but itself,  `kill *xvfb pid*` fails because there is no such process.

**Comment by neychev** [comment]
UPD2: On a blank-clear machine (just created instance) created docker (according to the instruction) and repeated the actions above. The result is the same. + any newly created docker with the same recipe fails to use plt.

**Comment by justheuristic** [comment]
Afair from offline conersations, this boiled down to issues with our internal VM technology stack, innit?
If so, i'll close issue. Otherwise pls clarify.
