### ISSUE TITLE
Image of the network to build missing

### ISSUE THREAD

**Issue by Ridhwanluthra** [yandexdataschool/Practical_RL#158]
https://github.com/yandexdataschool/Practical_RL/blob/master/week4_approx_rl/seminar_pytorch.ipynb
In this file the image on which to base the network is missing

**Comment by NickVeld** [comment]
If your conclusion is based on the Github preview, check it in Jupyter. It can be the preview issue.

**Comment by Pastafarianist** [comment]
Thank you for your report!

We are aware of broken links, and the process of fixing them is tracked in https://github.com/yandexdataschool/Practical_RL/issues/84. Are you referring to the very first link from that issue (https://s14.postimg.org/uzay2q5rl/qlearning_scheme.png)?

**Comment by Ridhwanluthra** [comment]
@NickVeld I checked in preview and jupyter
@Pastafarianist that's cool, and yes that image. anyways there is just 1 image in that entire nb
