### ISSUE TITLE
week1 LunarLander swig fix

### ISSUE THREAD

**Issue by Scitator** [yandexdataschool/Practical_RL#16]
If you use old swig lib for LunarLander-v2, you may get an error. See this issue for solution:
https://github.com/openai/gym/issues/100

PS.Cause it was hard to find in notebook.

**Comment by justheuristic** [comment]
thanks! We'll keep that thing for a while. 
Also, here's what helped us on ubuntu14 - https://github.com/yandexdataschool/Practical_RL/blob/master/Dockerfile#L5-L13

**Comment by justheuristic** [comment]
a loooong while :)

**Comment by justheuristic** [comment]
Gathered this and similar tips [here](https://github.com/yandexdataschool/Practical_RL/wiki/Troubleshooting-guide)
