### ISSUE TITLE
week3/qlearning is difficult to pass for wrong reasons

### ISSUE THREAD

**Issue by dniku** [yandexdataschool/Practical_RL#200]
It is not a particularly enlightening assignment, but it is difficult to obtain mean reward ≥100: see [this thread](https://www.coursera.org/learn/practical-rl/discussions/all/threads/qNJXx2wOEemjiRJSvqYBEg) for example. There are multiple factors in this:

* tuning discretization params is tedious and students are given little guidance in this
* `CartPole-v0` is wrapped in `TimeLimit(200)` by default which limits the amount of experience gained per episode

Possible options:

* Relax requirements for passing the assignment
* Write hints for discretization
* Remove `TimeLimit`

**Comment by justheuristic** [comment]
will: add tips, remove timelimit, fix in on-campus
will not: touch coursera

**Comment by Pastafarianist** [comment]
More threads:

* https://www.coursera.org/learn/practical-rl/discussions/all/threads/RcOWWV_CEei_YA56pmzPTA (long discussion with some tips)
* https://www.coursera.org/learn/practical-rl/discussions/all/threads/HQUTOZLSEemiLgpeSTtHXg (a detailed and well-written demonstration of suffering)
