### ISSUE TITLE
coursera/week4/quiz2/q2 is ambiguous

### ISSUE THREAD

**Issue by Pastafarianist** [yandexdataschool/Practical_RL#217]
Relevant reports:

* https://www.coursera.org/learn/practical-rl/discussions/all/threads/Tqd4O4M6EeiKFw5LeHdHQg
* https://www.coursera.org/learn/practical-rl/discussions/weeks/4/threads/nTEvymK8EeiwJgop3LmPTg
* https://www.coursera.org/learn/practical-rl/discussions/all/threads/Zq2P8YuREemQIQ6bNwggQA

Link to quiz: https://www.coursera.org/learn/practical-rl/exam/HCqgP/sarsa-and-qleaning

**Comment by Pastafarianist** [comment]
New [comment](https://www.coursera.org/learn/practical-rl/discussions/all/threads/Tqd4O4M6EeiKFw5LeHdHQg/replies/TuqALIUyEeibBw55Z5R0gg/comments/rI3EQZRaEemCdA4u0wWaDg) on the subject:

> The answer is SARSA has several stochasticity issues. And the other answer is All methods except SARSA use S,A,R and S' .
> However, both answers do not make sense, all methods in RL (Q , SARSA and Expected Sarsa) due to the nature of dynamic programming and bootstrapping have several source of stochasticity.
> Also, SARSA use S,A,R and S' like the other methods just it has to have A' in his computation as well.
> Any how, ambiguity has been the nature of this course.

**Comment by pshvechikov** [comment]
Done
