### ISSUE TITLE
coursera/week2/optimality quiz is confusing

### ISSUE THREAD

**Issue by Pastafarianist** [yandexdataschool/Practical_RL#227]
Forum: https://www.coursera.org/learn/practical-rl/discussions/all/threads/uEsJ3185EeicYBJ1mT_j9g

Quiz: https://www.coursera.org/learn/practical-rl/exam/GG4SV/optimality-in-rl

**Comment by pshvechikov** [comment]
Changed the feedback type of the quiz and several option formulations in q5. 
It should help people to receive feedback on mistakes. 
I am not convinced q5 or q1 is ambiguous; they both need to be carefully thought of.

**Comment by Pastafarianist** [comment]
One thing that is confusing with q1 is that the options are not mutually exclusive. Perhaps that could be changed?
