### ISSUE TITLE
How can i access the tensorboard at port 6000 ?

### ISSUE THREAD

**Issue by efotopoulou** [yandexdataschool/Practical_RL#231]
Hi all,
I deployed the suggested "Practical_RL" container by exposing also the port 6000 as follows:

```
docker run --rm -it -v `pwd`:/notebooks -p 8888:8888 -p 6000:6000 --name practical_rl justheuristic/practical_rl
```

Then i launced the tensorboard as follows:
```
# launch tensorflow the ugly way, uncomment if you need that
import os
port = 6000 + os.getuid()
print("Port: %d" % port)
#!killall tensorboard
os.system("tensorboard --logdir=./tboard --port=%d &" % port)

# show graph to tensorboard
writer = tf.summary.FileWriter("./tboard", graph=tf.get_default_graph())
writer.close()
```
And seems to be successfully deployed:

```
TensorBoard 1.13.1 at http://216080ec430d:6000 (Press CTRL+C to quit)
```

But still.....i can not access the tensorboard at http://localhost:6000/

Seems to be a docker misconfiguration but still....any idea?????

Thanks a lot in advance.

**Comment by Pastafarianist** [comment]
Am I correct that you are using Chrome and getting the `ERR_UNSAFE_PORT` error?

![image](https://user-images.githubusercontent.com/1315874/60807939-c0e2e000-a18f-11e9-91f7-7ec102b9713e.png)

**Comment by efotopoulou** [comment]
yes you are right! 
Any idea????
:-):-):-)

**Comment by Pastafarianist** [comment]
My guess is that the instructions have not been tested with a recent version of Chrome.

The [first link from Google](https://superuser.com/questions/188006/how-to-fix-err-unsafe-port-error-on-chrome-when-browsing-to-unsafe-ports) says that there are two options:

* Start Chrome with the `--explicitly-allowed-ports=6000` flag
* Edit the port from `6000` to something else, like `6006`

I would suggest doing the latter. A quick solution is to change the `-p` switch for `docker run` from `6000:6000` to `6006:6000`. A cleaner solution is to change it to `6006:6006` and also to modify the Tensorboard startup command to default to the port `6006`.

**Comment by efotopoulou** [comment]
many thanks for the support! i am a newbie...
just changed the port and works like a charm!
