### ISSUE TITLE
It should be clear why we have multiple Dockerfiles

### ISSUE THREAD

**Issue by dniku** [yandexdataschool/Practical_RL#232]
The reason is discussed in #42:

> practical_rl/Dockerfile is for binder
practical_rl/docker/Dockerfile is for local containers.

> Would be nice to converge to a single dockerfile but turns out binder adds some commands on top of your dockerfile for it to work AND depends on andrewosh/binder-base AND has an issue with maximum number of linked C libraries which is bad news if you want both gym env.render and pytorch under python3.

> The current best strategy (imho) is to wait for binder to fix the issue. If you have any better ideas (i aint pro w/ docker), they're most welcome.

However, this should be mentioned in the comments in the Dockerfiles themselves and/or in the Readmes.

**Comment by dniku** [comment]
Binder has [docs](https://mybinder.readthedocs.io/en/latest/tutorials/dockerfile.html) on how to use Dockerfiles, which links to a [page](https://mybinder.readthedocs.io/en/latest/introduction.html#preparing-repositories) that explains how to do without a Dockerfile. Need to investigate whether it is possible to use `environment.yml` instead of Dockerfile.

**Comment by yhn112** [comment]
resolved in #440
