### ISSUE TITLE
Mistake in week02_value_based/seminar_vi?

### ISSUE THREAD

**Issue by jaapjorisjaap** [yandexdataschool/Practical_RL#242]
When testing the correctness of the `get_new_state_value`, the asserted value is `0.69`. This should be `1.08`, because of

```
Q_i(s2, a0) = P(s1 | s2, a0) * [r(s2, a0, s1) + gamma * V_i(s1)] +
              P(s2 | s2, a0) * [r(s2, a0, s2) + gamma * V_i(s2)]
            = 0.4 * (0 + 0.9 * 0) +
              0.6 * (0 + 0.9 * 2)
            = 1.08
```

Hence this:

```python
assert np.allclose(get_new_state_value(mdp, test_Vs, 's2', 0.9), 0.69)
```

Should become:

```python
assert np.allclose(get_new_state_value(mdp, test_Vs, 's2', 0.9), 1.08)
```

**Comment by dniku** [comment]
This is likely caused by https://github.com/yandexdataschool/Practical_RL/commit/29d7c4c3a6b57004267290a1b85d0a01180a8bd7#diff-3a53300b1308c29952050416c377c926R49
