### ISSUE TITLE
correct links to Sutton's book

### ISSUE THREAD

**Issue by IvanKush** [yandexdataschool/Practical_RL#26]
It was moved

correct link is
http://incompleteideas.net/sutton/book/ebook/the-book.html

**Comment by bestxolodec** [comment]
I would say correct link now is
http://incompleteideas.net/sutton/book/the-book-2nd.html


вс, 16 апр. 2017 г. в 11:43, Ivan Kush <notifications@github.com>:

**Comment by justheuristic** [comment]
Thank you! Fixed the links!
