### ISSUE TITLE
Implement grader for coursera/week6/seq2seq

### ISSUE THREAD

**Issue by dniku** [yandexdataschool/Practical_RL#263]
There is a TODO in the [corresponding notebook](https://github.com/yandexdataschool/Practical_RL/blob/coursera/week6_outro/seq2seq/practice_tf.ipynb).

**Comment by Scitator** [comment]
Sorry, due to the large workload, I'm afraid I will not have time to fix this issue.

**Comment by dniku** [comment]
Done in #268.
