### ISSUE TITLE
Bug in MDP data in week02_value_based/seminar_vi.ipynb

### ISSUE THREAD

**Issue by slonoten** [yandexdataschool/Practical_RL#264]
It's bug in mdp data that ruins assertions for ```get_new_state_value``` function. It should be 
```   
 's2': {
        'a0': {'s0': 0.4, 's1': 0.6},
```
instead of
```   
 's2': {
        'a0': {'s0': 0.4, 's2': 0.6},
```
MDP diagramm in notebook has a right transition from this 's2'->'a0' action.

**Comment by dniku** [comment]
We fixed assertions for this notebook around a week ago. Can you check whether the error is still there with the latest version?

**Comment by slonoten** [comment]
I have checked. Sorry, my it's fault, I was messed up with diagramm which is still not updated.
