### ISSUE TITLE
Image scaling in A3C (coursera)

### ISSUE THREAD

**Issue by falceeffect** [yandexdataschool/Practical_RL#304]
See https://www.coursera.org/learn/practical-rl/discussions/all/threads/M7jJWvWOEemPLQpLUzO1ig

Looks like modern versions of OpenAI Gym do the scaling themselves. This leads to double division by 255, which produces near-zero values in image tensors. And that, of course, prevents the algorithm from ever converging. Removing division by 255 from PreprocessAtari solves the problem. 

I've spent a lot of time trying to figure out what was wrong with my code only to find this stupid inconsistency days later..

**Comment by dniku** [comment]
Thank you for the report! Would you mind submitting a pull request to remove the unnecessary normalization?

**Comment by falceeffect** [comment]
I've submitted a PR. Please, make sure that this doesn't break something on coursera environments or whatever else, because I tested it only locally.

**Comment by dniku** [comment]
Closed via #305.
