### ISSUE TITLE
pytorch version of coursera notebook is outdated

### ISSUE THREAD

**Issue by HyoungsungKim** [yandexdataschool/Practical_RL#313]
I cannot make a tensor using `torch.tensor(..., dtype = torch.float32)`

I got this error

```python
AttributeError: module 'torch' has no attribute 'float32'
```
I submitted using my local environment and i got correct. Therefore, i think it is not a problem of source code.

My pytorch is 1.2.0. I checked coursera's pytorch using `torch.__version__` and it was 0.1.12

This is my source code [source](https://github.com/HyoungsungKim/Study-Reinforcement-learning/blob/master/Practical_RL/week04/seminar_pytorch.ipynb)

If you don't mind please check version of pytorch.

And really thanks for awesome lecture and assignment. It is very helpful.

**Comment by dniku** [comment]
Technically, we don't (yet) support PyTorch for the Coursera assignments, and the version of PyTorch that is installed in the Coursera containers is ancient. Support is planned though. I think we can ask Coursera to update PyTorch to the latest version, as nothing should break down because of that.

**Comment by dniku** [comment]
Coursera have updated their PyTorch version to 1.4.0.
