### ISSUE TITLE
Presentations are missing

### ISSUE THREAD

**Issue by chanansh** [yandexdataschool/Practical_RL#325]
Can you please add the presentations?

**Comment by justheuristic** [comment]
I am afraid the presentations are there.
Here's an example of how to get week1 slides:
(1) go to the first week's folder
![image](https://user-images.githubusercontent.com/3491902/74418095-e25c2680-4e58-11ea-9b51-e75312f2e6e8.png)

(2) Click "Lecture slides" in the readme
![image](https://user-images.githubusercontent.com/3491902/74418130-f3a53300-4e58-11ea-9b50-69d850d3d653.png)

(3) press "Download"
![image](https://user-images.githubusercontent.com/3491902/74418185-0a4b8a00-4e59-11ea-9c82-e6d349b9f11f.png)

**Comment by chanansh** [comment]
sorry about that. thanks. which version is compatible with the Coursera course?

**Comment by dniku** [comment]
Also, in week 1, we have a [section](https://www.coursera.org/learn/practical-rl/supplement/RwKQM/lecture-slides) which contains a link to slides on Google Drive: https://drive.google.com/open?id=1namOzkac2RZoDQe-M9876OdZp6IJ2lcL
