### ISSUE TITLE
(Russian) Видео для Episode 3.5 - лекция по Deep Learning 101

### ISSUE THREAD

**Issue by roboserg** [yandexdataschool/Practical_RL#35]
Неделя 3.5, вы указываете в lecture slides слайды из лекции Яндекс по Deep Learning (https://yadi.sk/i/yAO2AJ3M3EKP8g)

Если ли видео по этой лекции?

**Comment by justheuristic** [comment]
К сожалению, нет (это моя лекция, поэтому точно знаю, что я её не писал), но мб найдём что-то получше.

**Comment by justheuristic** [comment]
(ссылки переделали)
