### ISSUE TITLE
recap_ml np.argmax off by 1 error

### ISSUE THREAD

**Issue by flowersw** [yandexdataschool/Practical_RL#406]
macos 10.15.4
python 3.7.6
numpy  1.18.1 
pandas  1.0.3  

Was just going through the helpful recap_ml refresher in week01
```
print("Max ticket price: ", np.max(data["Fare"]))
print("\nThe guy who paid the most:\n", data.loc[np.argmax(data["Fare"])])
```
I don't know why, but this is giving back

```
Max ticket price:  512.3292

The guy who paid the most:
 Survived                       1
Pclass                         1
Name        Cherry, Miss. Gladys
Sex                       female
Age                           30
SibSp                          0
Parch                          0
Ticket                    110152
Fare                        86.5
Cabin                        B77
Embarked                       S
Name: 258, dtype: object
```

clearly the fare of 86.5 != 512.3292 . It's returning index 630, not 631, I'm not sure why

Perhaps there was an api change in pandas / numpy?

I was able to get the right answer by using

`print(data.loc[data['Age'].idxmax()])`

**Comment by dniku** [comment]
The problem was most likely introduced in https://github.com/yandexdataschool/Practical_RL/pull/331. Looking into it.

**Comment by dniku** [comment]
Hmm, no, #331 actually _fixed_ that issue. Which version of the notebook are you using?

**Comment by flowersw** [comment]
Yes, I think you're right. Looks like it should simply be `iloc` instead of `loc` -> 
`print("\nThe guy who paid the most:\n", data.iloc[np.argmax(data["Fare"])])`

I tried to pull down from master just this morning...let's see

When I run `git tag` i see `spring19`. 


And git log shows

```
commit 05105b5a7da9db951ee0ea79dbb16eaf4e089d20 (HEAD -> master)
Merge: 7acb8d6 ff1f81e
Author: will flowers <wflowers@redhat.com>
Date:   Fri May 1 10:44:14 2020 -0400

    Merge branch 'master' of https://github.com/yandexdataschool/Practical_RL

commit ff1f81e9d470bcacc2214cc8d453d520a541fe7b (origin/master, origin/HEAD)
Merge: 4819885 2520bd7
Author: justheuristic <justheuristic@gmail.com>
Date:   Tue Feb 4 17:11:41 2020 +0300

    Merge pull request #316 from yandexdataschool/master-week6-fix-cartpole-timelimit

    [week6] Fix accidental TimeLimit in CartPole
```

**Comment by flowersw** [comment]
looks like `spring 20` is the latest branch, not master. I'll switch over to that one, unless you recommend not to

**Comment by dniku** [comment]
Ah, I see. Can you run `git checkout spring20`? It's the current default branch, which will go away at the end of this semester.

**Comment by flowersw** [comment]
that fixed it - thanks!!!
