### ISSUE TITLE
Make videos work more reliably

### ISSUE THREAD

**Issue by dniku** [yandexdataschool/Practical_RL#408]
Our usual way for displaying videos (the `HTML(...)` cell) doesn't work for me, but it works for @yhn112 (both tests were in Colab). Need to fix that.

**Comment by nokados** [comment]
It doesn't work for me too. I fixed it like this:
https://stackoverflow.com/questions/57377185/how-play-mp4-video-in-google-colab

**Comment by dniku** [comment]
Thank you for the link! I've merged a fix into `master`; we'll merge it into `coursera` at some point.
