### ISSUE TITLE
Binder to Launch VM not working

### ISSUE THREAD

**Issue by prashantksharma** [yandexdataschool/Practical_RL#46]
After clicking on the "launch|binder" button, I get the following error.
![selection_127](https://user-images.githubusercontent.com/5937244/36303496-5a09c250-1332-11e8-8c51-a8ee3a411e27.png)

**Comment by justheuristic** [comment]
(i think we managed to get it working. Binder still goes dark time to time, but on average it works more often than it doesn't)

**Comment by justheuristic** [comment]
If the issue persists, reopen this.
