### ISSUE TITLE
Complete code

### ISSUE THREAD

**Issue by Yuanzhuo-Liu** [yandexdataschool/Practical_RL#466]
Hello! Could you  you tell me where to find the complete code about the homework? I want to learn the better code, but I can't find it. Is there any answer for the homework or any solutions for the homework? Thanks!

**Comment by dniku** [comment]
Hi. We don't publish the solutions for the assignments because that would have violated the Coursera Honor Code (as I'm assuming you are coming from Coursera). However, in general, our assignments are in fill-in-the-blanks style, so there isn't much code to learn from.
