### ISSUE TITLE
The links can't be opened now

### ISSUE THREAD

**Issue by zlw21gxy** [yandexdataschool/Practical_RL#480]
Almost all the links about this course can't be opened (instead of those YouTube video), may I ask what happened.

**Comment by dniku** [comment]
Not sure what you mean. Can you give an example of a link that doesn't work?

**Comment by zlw21gxy** [comment]
I will close this issue, https://yadi.sk/i/-EUHXUXOTC5t9Q, some links like this can't be open due to my firewall setting, so I use other devices to download the PPT eventually. Thanks for your attention.
