### ISSUE TITLE
NoSuchDisplayException in week4_approx_rl/seminar_pytorch.ipynb

### ISSUE THREAD

**Issue by nokados** [yandexdataschool/Practical_RL#49]
In first block replace `if os.environ.get("DISPLAY") is not str` to `if type(os.environ.get("DISPLAY")) is not str`

**Comment by justheuristic** [comment]
Hi! Thank you for pointing it out. Fixed for week4, will check for further weeks
https://github.com/yandexdataschool/Practical_RL/commit/0bf1b846d6743558243373083734df6b34757157

**Comment by justheuristic** [comment]
turns out this snippet was was added to notebooks by authors copy-pasting it from other notebooks. At some point in time, we had several "normal" versions and one "corrupted strain" which ppl (incl. me) blindly copied from :)

Thanks again!
