### ISSUE TITLE
In Coursera branch, why do the last commit deleted the grading module for week1?

### ISSUE THREAD

**Issue by HaoLuo2627** [yandexdataschool/Practical_RL#501]
The last commit in Coursera branch deleted the grading module for week1, and this sets barriers for us students to submit the assignments and pass the course. I don't know why.
Besides, the coursera forum is not very active in the recent years. Is the Coursera course an archived version?
Thank you.

**Comment by igor-cheb** [comment]
same question here, could someone pls address this

**Comment by ashaba1in** [comment]
This course is closed by the Coursera due to its policy, so I removed the course to a new platform and didn’t change the branch. Turned out that is can still be accessed by users who started it before march. I reverted all changes, it should work now.
