### ISSUE TITLE
Issue with Slides in Materials of #4

### ISSUE THREAD

**Issue by AI-Ahmed** [yandexdataschool/Practical_RL#502]
Slides in the Materials of #4_approx_rl are not available.

Link to the materials: https://github.com/yandexdataschool/Practical_RL/tree/master/week04_approx_rl#materials
Screenshot:
![image](https://user-images.githubusercontent.com/72295771/179198258-b331de5c-973b-47bd-b026-7b561409cdb0.png)

**Comment by justheuristic** [comment]
@Fritz449 Hi! It looks like that link used to point to your slides. Could you please check this one?

**Comment by Fritz449** [comment]
Something bad happened to this presentation :(
You can still read the slides at the video of the lecture: https://disk.yandex.ru/i/Gd9yWV1dpuB7BQ
We plan to fix this presentation later.

**Comment by AI-Ahmed** [comment]
It would be my pleasure, @Fritz449. But unfortunately, I don't understand Russian. I wish I could!

**Comment by Hacker1337** [comment]
@Fritz449 Hello. Are there any updates on this? It looks like the issue is still present.

**Comment by dniku** [comment]
Hi! Unfortunately, the original presentation is lost, so we've recreated it from scratch. Please find it here:

[ysda_practical_rl_lecture_04.pdf](https://github.com/yandexdataschool/Practical_RL/files/15286337/ysda_practical_rl_lecture_04.pdf)
