### ISSUE TITLE
Do you provide solutions?

### ISSUE THREAD

**Issue by GoingMyWay** [yandexdataschool/Practical_RL#52]
Hi, thanks for developing such wonderful course for beginners, I have finished some tasks, I wonder do you provide solutions to these tasks so that I can check my homework? Thank you!

**Comment by justheuristic** [comment]
Hi!
Unfortunately we don't provide solutions publicly: the course is taught on-campus in HSE & YSDA, we don't want our students to submit the solutions with minor changes.
We added automatic tests and formal checks (e.g. mean reward >= threshold) to some parts, but they're still in progress. 
If there's anything in particular you want to sanity-check, feel free to ask, e.g. here.
