### ISSUE TITLE
week1 - MountainCar-v0

### ISSUE THREAD

**Issue by nambrot** [yandexdataschool/Practical_RL#56]
I started doing this class this week and I really like how well everything was thought out for self-learning. I really like the notebooks. I feel like I got a good grasp on Crossentropy, completing the notebook. However, I then tried to apply the learnings to `MountainCar-v0`, but have been quite stuck. It seems like the initial policy intialization never allows the agent to get the car once onto the mountain, thus our elite states do not contain any meaningful progress we can learn from.

Are there any hints that I could use in how to overcome this challenge?

**Comment by justheuristic** [comment]
Hi!
Yeah, that's exactly right - solving mountaincar either requires a lot of trials or your agent exploring the environment more efficiently. Exploration is covered in more detail around week5, at week1 the idea was that you would just beat it by playing a lot of sessions. And yes, it's better if you set time limit for mountaincar to something around 1k-10k (see instructions in the ipynb).

So far as i remember, in current openai gym, mountaincar terminates automatically after 200 steps. To mitigate that, try ```env = gym.make("MountainCar-v0").env``` . 
The envs gym creates are in fact layered, there's the base env and a wrapper around that. The .env above goes from TimeLimit(200) wrapper to the base env stored inside it.

**Comment by nambrot** [comment]
Thanks for the answer!
