### ISSUE TITLE
Issues with week2 main assignment

### ISSUE THREAD

**Issue by Omrigan** [yandexdataschool/Practical_RL#6]
Even with python2 and a working display main assignment sometimes fails.

@justheuristic What issues did you meet?

**Comment by justheuristic** [comment]
err... fatal opengl errors of doom?

**Comment by justheuristic** [comment]
Okay, so far
 "students want their homework to evaluate quickly without rendering for 5 minutes",
 "the rendering window crashes the whole xsession under older opengl"
and that's all.
We probably need to (1) add a flag for variable time duration and (2) add a friendly warning for those with older GL that they should prefer ./alternative.

I'll close the issue as the deadline for hw2 is over and add all the requests to the wiki.
