### ISSUE TITLE
dns_server_failure when trying to open jupyter URL in browser

### ISSUE THREAD

**Issue by maxblumental** [yandexdataschool/Practical_RL#69]
I run docker on my Ubuntu like this:
`$ sudo docker run -it -v $(pwd):/notebooks -p 8888:8888  justheuristic/practical_rl sh ../run_jupyter.sh`

In output I saw this suggestion:
`Copy/paste this URL into your browser when you connect for the first time, to login with a token:
 http://9cd070fb79bf:8888/?token=ad1a5a0aab43efb47a9a805388fcf508d0b5f84a16e4542b&token=ad1a5a0aab43efb47a9a805388fcf508d0b5f84a16e4542b`

My browser reacts:

`Network Error (dns_server_failure)`
`Your request could not be processed because an error occurred contacting the DNS server.`
`The DNS server may be temporarily unavailable, or there could be a network problem.`

Did anyone face this problem?

**Comment by justheuristic** [comment]
It should probably be `localhost:8888/?token=<your_token>` instead, not 9cd070fb79bf

If dor some reason it doesn't work, try  `127.0.0.1:8888/?token=<your_token>`
