### ISSUE TITLE
get token but cannot run in my browser

### ISSUE THREAD

**Issue by nathanielwei** [yandexdataschool/Practical_RL#71]
PS C:\Users\Nathaniel> docker run 491528bcff41
Unable to find image '491528bcff41:latest' locally
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: pull access denied for 491528bcff41, repository does not exist or may require 'docker login'.
See 'C:\Program Files\Docker\Docker\Resources\bin\docker.exe run --help'.
PS C:\Users\Nathaniel> docker run justheuristic/practical_rl:latest
[I 13:27:41.201 NotebookApp] Writing notebook server cookie secret to /root/.local/share/jupyter/runtime/notebook_cookie_secret
[I 13:27:41.379 NotebookApp] Serving notebooks from local directory: /notebooks
[I 13:27:41.379 NotebookApp] 0 active kernels
[I 13:27:41.379 NotebookApp] The Jupyter Notebook is running at:
[I 13:27:41.379 NotebookApp] http://6084fd93b11e:8888/?token=81a441a15748a2f85280d14a39bcd237b1e16c6ad0ff6972
[I 13:27:41.379 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 13:27:41.380 NotebookApp]

    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://6084fd93b11e:8888/?token=81a441a15748a2f85280d14a39bcd237b1e16c6ad0ff6972&token=81a441a15748a2f85280d14a39bcd237b1e16c6ad0ff6972

**Comment by justheuristic** [comment]
Does it work if u replace http://<whatever_is_there>:8888/?token=<your_token> with ```http://127.0.0.1:8888/?token=<your_token>```?

**Comment by nathanielwei** [comment]
Thanks so much! 
This can work well!
