### ISSUE TITLE
Many video are removed

### ISSUE THREAD

**Issue by semochka** [yandexdataschool/Practical_RL#81]
Hi,

Thank you for the awesome course!!!! Unfortunately many of the videos show the following:

Nothing found
The owner either removed the files or restricted access, or there's a typo in the link.

Thank you for fixing it,
-Simon

**Comment by justheuristic** [comment]
Could you please point to one of such videos? 
Maybe there was some access restriction. In either case, we'll re-upload it.

**Comment by semochka** [comment]
Everything works now - thank you very much!
