### ISSUE TITLE
Issue with overflow in practice_tensorflow.ipynb

### ISSUE THREAD

**Issue by GusHebblewhite** [yandexdataschool/Practical_RL#82]
I don't have the best grasp of this stuff so forgive me if this is just a misunderstanding.

So in this notebook (https://github.com/yandexdataschool/Practical_RL/blob/master/week4_%5Brecap%5D_deep_learning/practice_tensorflow.ipynb) in the very first few code cells we write a function and then use TF to speed it up. However as written, it seems like the cumulative sum of squares up to `10**8` will result in an integer quite a bit larger than can be encoded in int64. As suck both TF and naive numpy will give the wrong answer and the speed is misleading,

Maybe the operation should be changed to something that results in less large numbers. This would retain the large number of iterations (`10**8` for example) to show the dramatic speedup. Alternately, `10**6` iterations is OK with sum of squares.

**Comment by justheuristic** [comment]
Thank you for the report! We'll switch to int64 in the next release.
