### ISSUE TITLE
docker notebook raise Permission Error

### ISSUE THREAD

**Issue by Caijiawen** [yandexdataschool/Practical_RL#85]
I use the docker to set up environment , when i go into notebook it raised error below:

``
Server error: Traceback (most recent call last): File "/usr/local/lib/python3.5/dist-packages/tornado/web.py", line 1592, in _execute result = yield result File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 1133, in run value = future.result() File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result raise self._exception File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 326, in wrapper yielded = next(result) File "/usr/local/lib/python3.5/dist-packages/notebook/services/contents/handlers.py", line 112, in get path=path, type=type, format=format, content=content, File "/usr/local/lib/python3.5/dist-packages/notebook/services/contents/filemanager.py", line 431, in get model = self._dir_model(path, content=content) File "/usr/local/lib/python3.5/dist-packages/notebook/services/contents/filemanager.py", line 313, in _dir_model for name in os.listdir(os_dir): PermissionError: [Errno 13] Permission denied: '/notebooks'
``

**Comment by justheuristic** [comment]
try to 
`chmod -R 777 /your/path/to/notebooks`
Also pls tell us which operating system do you use.

**Comment by cameronbergh** [comment]
i have chmodded everything to 777 and i am still getting this on ubuntu 18.04

**Comment by dniku** [comment]
I have just tested that our setup works for me, so I have to ask you to provide enough information for me to reproduce the issue. Please describe your environment in detail. In particular:

* Which command are you using to launch Docker? Which directory are you executing it from?
* What exactly works fine if you `cd` to `/home/user`?
* Where are you executing `jupyter notebook --notebook-dir /media/user/nvme`? Within or outside of Docker? What output are you getting, and what do you expect?
