### ISSUE TITLE
`week3_model_free/sumbit.py` has bugged `submit_qlearning1` and `submit_qlearning1`

### ISSUE THREAD

**Issue by gvgramazio** [yandexdataschool/Practical_RL#89]
The functions `submit_qlearning1` and `submit_qlearning1` are broken. They keep returning an error in the submission. The workaround is the following:

 - After the first part of the assignment substitute 
   ```
   from submit import submit_qlearning1
   submit_qlearning1(rewards, <YOUR-EMAIL>, <TOKEN>)
   ```
   with
   ```
   rewards1 = rewards.copy()
   ```
 - After second part of the assignment, substitute
   ```
   from submit import submit_qlearning2
   submit_qlearning2(rewards,  <YOUR-EMAIL>, <TOKEN>)
   ```
   with
   ```
   rewards2 = rewards.copy()
   ```
 - In the end, run
   ```
   from submit import submit_qlearning_all
   submit_qlearning_all(rewards1, rewards2, <YOUR-EMAIL>, <TOKEN>)
   ```
   because the `submit_qlearning_all` seems to not be bugged.

This workaround was suggested to me by Jay Glascoe on the Coursera forum.

**Comment by Scitator** [comment]
Hi, 

Thanks for workaround. Now in master branch.
