### ISSUE TITLE
CartPole-v0

### ISSUE THREAD

**Issue by neychev** [yandexdataschool/Practical_RL#9]
I suggest to add into the HW that sometimes there is a limitation of max reward = 200.
To fix that instead of 
env = gym.make("CartPole-v0")
should be like that
env = gym.make("CartPole-v0").env

I guess, it has been said orally somewhere, but without this info it took additional hour to find out what's wrong.

**Comment by bestxolodec** [comment]
It was already added to homework description, see [tips](https://github.com/yandexdataschool/Practical_RL/blob/master/week1/crossentropy_method.ipynb). 
Maybe we should have one big readme file (independent of homework) with all bugs and tips which we have encountered. 
PS. It is additional chellange to train agent with this limitation. On CartPole and q-learning agent it is surely possible.

**Comment by justheuristic** [comment]
Yup. The problem is, this thing with 200 turns may well be a bug introduced by gym or be changed soon enough. If it persists until, say, april 1st , we'll add it by default.

**Comment by neychev** [comment]
Ok, thanks. 
I've suggested to create one file with all bugs/tips yesterday, several people endorsed this idea. 

P.S. to @bestxolodec 
It was a [HW2](https://github.com/yandexdataschool/Practical_RL/blob/master/week2/alternative/homework.ipynb) issue, no tips over there. I've missed that in HW1 part.
I've succeeded with tuning q-learning up to 198 average score over last 200 eps
