### ISSUE TITLE
get MCTS seminar to work

### ISSUE THREAD

**Issue by dniku** [yandexdataschool/Practical_RL#93]
Please see https://github.com/openai/gym/issues/1056. The `close` kwarg was removed at some point.

**Comment by justheuristic** [comment]
@neer201 , можно тебя попросить посмотреть на эту тетрадку в spring19 и завести её под новым Openai Gym?

Если будут сложности - пиши, поможем. Если идеи по улучшению или замене на что-то более крутое - они всегда приветствуются :)

Сейчас тетрадка лежит [тут](https://github.com/yandexdataschool/Practical_RL/tree/spring19/_under_construction/week_planning). Само занятие будет ориентировочно в середине марта, т.е. вопрос не самый срочный.

**Comment by neer201** [comment]
[8a5c682](https://github.com/yandexdataschool/Practical_RL/commit/8a5c682a9b992c0c115de5cdf263aa5613dbbc29) - поправил

@Pastafarianist Подскажи, пожалуйста, я добавил такие же исправление в ветку **coursera**. Надо ли их добавлять в ветку **coursera-deployed**? Как проверить, что на курсере все норм работает?

**Comment by Pastafarianist** [comment]
`coursera-deployed` не надо менять вручную. Эта ветка должна соответствовать коммиту, который выложен на курсере.

Если твой патч уже находится в ветке `coursera`, то вот [тут](https://github.com/yandexdataschool/Practical_RL/blob/coursera/deployment.md) есть инструкция по тому, как его задеплоить (и в том числе как поменять `coursera-deployed`). После этого надо будет зайти в задание как learner и протестить руками (убедиться, что изменения накатились¹, и что задание решается).

¹ Coursera не затирает изменённые файлы, так что перед публикацией лучше убедиться, что у тебя нужный ноутбук не отредактирован

**Comment by neer201** [comment]
Спасибо за быстрый ответ!

> ¹ Coursera не затирает изменённые файлы, так что перед публикацией лучше убедиться, что у тебя нужный ноутбук не отредактирован
Ммм, я уже зашел на курсеру, и решал этот ноутбук(чтобы как раз баги отловить). Я понял что он теперь не сбросится, правильно? Если да, то что делать?

**Comment by Pastafarianist** [comment]
Вообще, я не знаю, как именно Coursera трекает изменения, но подозреваю, что если ты зайдёшь в терминал Jupyter и сделаешь `git checkout week6_outro/practice_mcts.ipynb`, то этого будет достаточно. Или можно переименовать твою изменённую копию `practice_mcts.ipynb` во что-нибудь другое (Coursera отказывается только перезаписывать старые изменённые файлы, новые прекрасно перезаписываются).

Да, забыл: после того, как нажмёшь publish workspace, нужно будет ещё зайти в твой контейнер студента, приписать к URL `?forceRefresh=true` и перезагрузить страницу, иначе изменения не подтянутся.

**Comment by justheuristic** [comment]
Ваня благополучно обновил, осталось обновить на курсере

**Comment by dniku** [comment]
Coursera MCTS should work, however merge is still needed (#262) . Furthermore, there is a stray comment about `render(close=True)` that should be removed (#270).
