### ISSUE TITLE
Introductory Gym notebook throws a warning

### ISSUE THREAD

**Issue by Pastafarianist** [yandexdataschool/Practical_RL#97]
https://www.coursera.org/learn/practical-rl/notebook/IKHzO/openai-gym throws
```
WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
```
in cell 2.

**Comment by justheuristic** [comment]
This maaaay or may not be an issue with gym itself.
(давай в условную пятницу с этим разберёмся?)

**Comment by justheuristic** [comment]
Всё так, это косяк внутри gym-а, возможно лечится обновлением библиотеки

**Comment by Pastafarianist** [comment]
Note: no longer reproducible on my laptop (with the latest versions of all libraries installed).

**Comment by Pastafarianist** [comment]
Tested in Coursera env, no longer reproducible there either.
